Feat/follow
All-eatery/EatsFinder-BE pull request #69
Opened 2024-07-18 14:10 UTC by rim109

## 💡 PULL REQUEST

## #️⃣ 연관된 이슈

> #68 , #33, #50 

## 📝 작업 내용

> 
- 팔로우 기능을 구현했습니다.
- 프론트 분의 요청으로 이메일 인증 부분에서 인증 확인 api를 추가하였습니다.
- 회의 후 비밀번호 유효성을 맞췄습니다.

2024-07-18 15:23 UTC, go-tiger requested changes

2024-07-18 15:23 UTC, go-tiger commented on src/main/kotlin/com/eatsfinder/domain/email/service/EmailServiceImpl.kt
> +    }
아래 상황들 때문에 이메일에 유니크 키를 설정을 안해둔건데 위 코드에서는 그런 분을 체크하는게 없네요

1. 로컬계정을 가입하고 나중에 소셜로그인으로 가입했을때
2. 1번의 반대일 경우(선 소셜 가입 -> 후 로컬 가입)

2024-07-18 15:23 UTC, go-tiger commented on src/main/kotlin/com/eatsfinder/domain/email/service/EmailServiceImpl.kt
> +            throw ModelNotFoundException("email", "이미 가입되어 있는 이메일입니다 : $email")
예외처리가 not found 인가요?

2024-07-19 17:02 UTC, rim109 commented on src/main/kotlin/com/eatsfinder/domain/email/service/EmailServiceImpl.kt
> +            throw ModelNotFoundException("email", "이미 가입되어 있는 이메일입니다 : $email")
앗 네 ㅠㅠ 그래서 이미 존재한 예외라고 변경했습니다! 알려주셔서 감사해요

2024-07-19 17:04 UTC, rim109 commented on src/main/kotlin/com/eatsfinder/domain/email/service/EmailServiceImpl.kt
> +    }
아 맞네요,,, 수정해서 코드 올렸습니다!

소셜 로그인 후 로컬 회원가입 시도 했을때는 회원가입 가능
로컬 회원가입 후 소셜 로그인 시도 했을때는 회원가입 가능
로컬 회원가입 후 다시 로컬 회원가입을 시도했을 때 같은 이메일이라면 가입 불가능

이렇게 코드를 수정하고 테스트를 해보았지만 혹시 모르니 다시 한 번 확인 부탁드립니다!

2024-07-19 18:01 UTC, go-tiger approved these changes
고생하셨습니다.

2024-07-19 19:05 UTC, merged